name: Documentation
description: Documentation improvements
title: "[DOCS] "
labels:
  - "type: docs"

body:

- type: textarea
  id: description
  attributes:
    label: Description

- type: textarea
  id: details
  attributes:
    label: Details

- type: textarea
  id: affected-pages
  attributes:
    label: Affected Pages